/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.RosOpcua;

namespace RosSharp.RosBridgeClient.MessageTypes.RosOpcua
{
    public class CallMethodRequest : Message
    {
        public const string RosMessageName = "ros_opcua_srvs/CallMethod";

        public Address node { get; set; }
        public Address method { get; set; }
        public TypeValue[] data { get; set; }

        public CallMethodRequest()
        {
            this.node = new Address();
            this.method = new Address();
            this.data = new TypeValue[0];
        }

        public CallMethodRequest(Address node, Address method, TypeValue[] data)
        {
            this.node = node;
            this.method = method;
            this.data = data;
        }
    }
}
