/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RosOpcua
{
    public class ConnectRequest : Message
    {
        public const string RosMessageName = "ros_opcua_srvs/Connect";

        public string endpoint { get; set; }

        public ConnectRequest()
        {
            this.endpoint = "";
        }

        public ConnectRequest(string endpoint)
        {
            this.endpoint = endpoint;
        }
    }
}
