/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.RosOpcua;

namespace RosSharp.RosBridgeClient.MessageTypes.RosOpcua
{
    public class ListNodeResponse : Message
    {
        public const string RosMessageName = "ros_opcua_srvs/ListNode";

        public bool success { get; set; }
        public string error_message { get; set; }
        public Address[] children { get; set; }

        public ListNodeResponse()
        {
            this.success = false;
            this.error_message = "";
            this.children = new Address[0];
        }

        public ListNodeResponse(bool success, string error_message, Address[] children)
        {
            this.success = success;
            this.error_message = error_message;
            this.children = children;
        }
    }
}
