/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.RosOpcua;

namespace RosSharp.RosBridgeClient.MessageTypes.RosOpcua
{
    public class SubscribeRequest : Message
    {
        public const string RosMessageName = "ros_opcua_srvs/Subscribe";

        public Address node { get; set; }
        public string callback_topic { get; set; }

        public SubscribeRequest()
        {
            this.node = new Address();
            this.callback_topic = "";
        }

        public SubscribeRequest(Address node, string callback_topic)
        {
            this.node = node;
            this.callback_topic = callback_topic;
        }
    }
}
