/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.RosOpcua;

namespace RosSharp.RosBridgeClient.MessageTypes.RosOpcua
{
    public class WriteRequest : Message
    {
        public const string RosMessageName = "ros_opcua_srvs/Write";

        public Address node { get; set; }
        public TypeValue data { get; set; }

        public WriteRequest()
        {
            this.node = new Address();
            this.data = new TypeValue();
        }

        public WriteRequest(Address node, TypeValue data)
        {
            this.node = node;
            this.data = data;
        }
    }
}
