/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RosOpcua
{
    public class Address : Message
    {
        public const string RosMessageName = "ros_opcua_msgs/Address";

        public string nodeId { get; set; }
        public string qualifiedName { get; set; }

        public Address()
        {
            this.nodeId = "";
            this.qualifiedName = "";
        }

        public Address(string nodeId, string qualifiedName)
        {
            this.nodeId = nodeId;
            this.qualifiedName = qualifiedName;
        }
    }
}
