/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RosOpcua
{
    public class TypeValue : Message
    {
        public const string RosMessageName = "ros_opcua_msgs/TypeValue";

        //  This represents OPC-UA type-value pair
        public string type { get; set; }
        public bool bool_d { get; set; }
        public sbyte int8_d { get; set; }
        public byte uint8_d { get; set; }
        public short int16_d { get; set; }
        public ushort uint16_d { get; set; }
        public int int32_d { get; set; }
        public uint uint32_d { get; set; }
        public long int64_d { get; set; }
        public ulong uint64_d { get; set; }
        public float float_d { get; set; }
        public double double_d { get; set; }
        public string string_d { get; set; }

        public TypeValue()
        {
            this.type = "";
            this.bool_d = false;
            this.int8_d = 0;
            this.uint8_d = 0;
            this.int16_d = 0;
            this.uint16_d = 0;
            this.int32_d = 0;
            this.uint32_d = 0;
            this.int64_d = 0;
            this.uint64_d = 0;
            this.float_d = 0.0f;
            this.double_d = 0.0;
            this.string_d = "";
        }

        public TypeValue(string type, bool bool_d, sbyte int8_d, byte uint8_d, short int16_d, ushort uint16_d, int int32_d, uint uint32_d, long int64_d, ulong uint64_d, float float_d, double double_d, string string_d)
        {
            this.type = type;
            this.bool_d = bool_d;
            this.int8_d = int8_d;
            this.uint8_d = uint8_d;
            this.int16_d = int16_d;
            this.uint16_d = uint16_d;
            this.int32_d = int32_d;
            this.uint32_d = uint32_d;
            this.int64_d = int64_d;
            this.uint64_d = uint64_d;
            this.float_d = float_d;
            this.double_d = double_d;
            this.string_d = string_d;
        }
    }
}
